apiVersion: v1
kind: Pod
metadata:
  name: static-web-test-local-1
  labels:
    role: myrole
spec:
  containers:
    - name: web-1
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
